# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmVkZWIzYjY3YThlZWI5ZWZhZGQ1NzAyMGJhYmM1ZmE3ZDdiYWE3ZjEzZWVmMDBjZjJjYTkxMjA2MGQ4ZGQ4ZDJhZTQ1NmU0NWEzNWUyMTNkYjMyMWI4MTkwNTU2ZWM3NmNiMDYzMzViYWFjYWMwNmMzZGIxMDk4ZGIwZjY3OGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
